# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca89ae70ab041a821c60a0dbb2dd8cf216b6c339821a5c3ed3773e6469c06aa781e128881062297245c868bd76f50d62652a7209b8769d2c340e7902ba8e0fb3

test:
  secret_key_base: 81b66b14008b0a9c978c944e254888a15e330707722a65023571810848aa7b01d00c8a79d2e18d288587715437a9290d74ec4644dd711f96a4e7a0a87d86af4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
